### ISSUE TITLE
Licensing issue?

### ISSUE THREAD

**Issue by DeeJayhX** [jschicht/RunAsTI#1]
From what I can see, your project doesn't include a license, and [what that means](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license) is that no one can use it, as standard copyright laws apply.

If this is not what you intended, might I recommend the [Eclipse Public License](https://www.eclipse.org/legal/epl-v10.html)?

Also, where did you find a license for RunAsSystem and/or RunFromToken that allow you to distribute them in your program (the compiled exes)

**Comment by jschicht** [comment]
So I added a MIT license. Those compiled exe's are from some older projects of mine that was previously maintained at google code. They will likely never be updated.

**Comment by DeeJayhX** [comment]
Thank you very much, this is greatly appreciated by those trying to play by the rules lol!
