### ISSUE TITLE
does not work with regedit...

### ISSUE THREAD

**Issue by jayjupdhig** [jschicht/RunAsTI#10]
![runasti](https://user-images.githubusercontent.com/42765391/148190927-5ae7f1fb-ba5c-4921-a249-c2a3114bd913.JPG)

**Comment by jayjupdhig** [comment]
also not when i run console in non-admin mode...

why that?

i need to edit the ´HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkSetup2\Interfaces´ regedit key as described HERE: https://stackoverflow.com/questions/32093792/how-to-remove-extra-host-only-network-interfaces-created-by-vagrant-on-windows-1

**Comment by jayjupdhig** [comment]
-> https://forums.virtualbox.org/viewtopic.php?f=6&t=104892&p=511464#p511464

**Comment by kosuodhmwa** [comment]
i can confirm that it does not work with windows RDP connection.
